apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: java-microprofile-build-deploy-pipeline
spec:
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: build-deploy
      taskRef:
        name: java-microprofile-build-deploy-task
      resources:
        inputs:
        - name: git-source
          resource: git-source
        outputs:
        - name: docker-image
          resource: docker-image
      params:
      - name: appsody-deploy-file-name
        value: appsody-deploy.yaml
