apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: java-spring-boot2-manual-pipeline-run
spec:
  serviceAccount: kabanero-operator
  timeout: "1h0m0s"
  pipelineRef:
    name: java-spring-boot2-build-deploy-pipeline 
  trigger:
    type: manual
  resources:
    - name: git-source
      resourceRef:
        name: git-source
    - name: docker-image
      resourceRef:
        name: docker-image
